name: Count Words In Md

on:
  pull_request:
  push:

permissions:
  contents: read

jobs:
  count-md-words:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2 #v4
        with:
          persist-credentials: false

      - name: Set up Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 #v4.03
        with:
          node-version: '20'

      - name: Run word count script
        run: node scripts/word-count/main.js courses
        

