name: Count Words In Md

on:
  pull_request:
  push:

jobs:
  count-md-words:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Run word count script
        run: node scripts/count-words.js courses
